### ISSUE TITLE
pam no longer supports @include?

### ISSUE THREAD

**Issue by seefood** [voxpupuli/puppet-googleauthenticator#11]
after I ram the module, these started to show up in the logs:

```
Jun 23 10:05:44 mon-app2 sshd[19048]: PAM (sshd) illegal module type: @include
Jun 23 10:05:44 mon-app2 sshd[19048]: PAM pam_parse: expecting return value; [...google-authenticator-all-users]
Jun 23 10:05:44 mon-app2 sshd[19048]: PAM (sshd) no module name supplied
Jun 23 10:05:44 mon-app2 sshd[19048]: pam_unix(sshd:auth): check pass; user unknown
```

could it be that pam on centos/RHEL 7 no longer supports @include lines?!

**Comment by raphink** [comment]
PAM is managed very differently between distributions, but I'd be surprised if this was not supported anymore... systemd maybe?

**Comment by seefood** [comment]
Well, it seems the error reports are coming from sshd, when using PAM. Nothing to do with systemd as far as I see. Should I patch the code to put in the line instead of an include? Shouldn't be too difficult.
